### ISSUE TITLE
moveSAN throws error instead of returning Left Noparse

### ISSUE THREAD

**Issue by JaapJoris** [ArnoVanLumig/chesshs#2]
When the `moveSAN` function is called with an invalid SAN string, the program crashes instead of returning `Left Noparse`. I posted a minimal example in this [StackOverflow question](http://stackoverflow.com/questions/32056598/how-to-handle-runtime-errors-in-haskell).

Furthermore, the `moveSAN` function never returns any of the `WrongTurn, NoPiece, IsCheck, CausesCheck, InvalidMove, OverPiece`, or `CapturesOwn` values, instead it always returns `Noparse` on any invalid move.

**Comment by ArnoVanLumig** [comment]
Thanks for reporting this. To be honest, the `moveSAN` function was mostly created for the purpose of unit testing... Quite an oversight though, I'm sorry.

I probably won't have time to fix this any time soon. Of course you're welcome to create a pull request if you feel up to it :-).

**Comment by JaapJoris** [comment]
I'm using `moveSAN` to process user input, so I should probably rewrite it as an actual parser. I don't feel I'm up to it yet, but who knows what I might come up with in the future!
